# Generated by Django 5.1.5 on 2025-05-07 06:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tokenizer",
            name="model",
        ),
        migrations.AddField(
            model_name="labelfile",
            name="task",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
