# version: '3.9'

services:

  # pgadmin
  pgadmin:
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - 8081:80

  # minio
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  # Modality Django App
  modality:
    container_name: modality-service
    build: ./backend/modality_service
    volumes:
      - ./backend/modality_service:/app
    ports:
      - "8002:8002"
    env_file:
      - ./backend/modality_service/.env

    depends_on:
      - modality_db

  # Modality DB
  modality_db:
    image: postgres:15
    container_name: modality_db
    environment:
      POSTGRES_DB: modality_db
      POSTGRES_USER: modality_user
      POSTGRES_PASSWORD: modality_pass
    volumes:
      - modality_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # Upload Django App
  upload:
    container_name: upload-service
    build: ./backend/upload_service
    volumes:
      - ./backend/upload_service:/app
    ports:
      - "8003:8003"
    env_file:
      - ./backend/upload_service/.env
    depends_on:
      - upload_db

  # Upload DB
  upload_db:
    image: postgres:15
    container_name: upload_db
    environment:
      POSTGRES_DB: upload_db
      POSTGRES_USER: upload_user
      POSTGRES_PASSWORD: upload_pass
    volumes:
      - upload_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  # Explanation Django App
  explanation:
    container_name: explanation-service
    build: ./backend/explanation_service
    volumes:
      - ./backend/explanation_service:/app
    ports:
      - "8005:8005"
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    env_file:
      - ./backend/explanation_service/.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - explanation_db

  # Explanation DB
  explanation_db:
    image: postgres:15
    container_name: explanation_db
    environment:
      POSTGRES_DB: explanation_db
      POSTGRES_USER: explanation_user
      POSTGRES_PASSWORD: explanation_pass
    volumes:
      - explanation_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  # Gateway Django App
  gateway:
    container_name: gateway-service
    build: ./backend/gateway_service
    volumes:
      - ./backend/gateway_service:/app
    ports:
      - "8001:8001"
    depends_on:
      - modality

volumes:
  modality_data:
  upload_data:
  explanation_data:
  minio_data:

