# Generated by Django 5.1.5 on 2025-05-14 13:50

from django.db import migrations
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ("modality_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
    ]
