# Generated by Django 5.1.5 on 2025-05-14 14:30

from django.db import migrations, models
import uuid

def create_modality_task(apps, schema_editor):
    Modality = apps.get_model('modality_app', 'Modality')
    Task = apps.get_model('modality_app', 'Task')
    modality_names = ['Computer Vision', 'Natural Language Processing', 'Tabular Processing']
    for item in modality_names:
        modality, created = Modality.objects.get_or_create(
            name=item,
        )

class Migration(migrations.Migration):

    dependencies = [
        ("modality_app", "0002_remove_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True),
        ),

    migrations.RunPython(create_modality_task),
    ]
