# Generated by Django 5.1.5 on 2025-05-14 15:40

from django.db import migrations
import uuid

def create_tasks(apps, schema_editor):
    Modality = apps.get_model('modality_app', 'Modality')
    Task = apps.get_model('modality_app', 'Task')
    computer_vision_tasks = ['Image Classification', 'Image Segmentation']
    nlp_tasks = ['Text Classification', 'Question Answering']
    tabular_tasks = ['Tabular Classification']

    computer_vision_modality_id = Modality.objects.get(name='Computer Vision')
    nlp_modality_id = Modality.objects.get(name='Natural Language Processing')
    tabular_modality_id = Modality.objects.get(name='Tabular Processing')

    for item in computer_vision_tasks:
        task, created = Task.objects.get_or_create(
            name=item,
            modality=computer_vision_modality_id
        )

    for item in nlp_tasks:
        task, created = Task.objects.get_or_create(
            name=item,
            modality=nlp_modality_id
        )

    for item in tabular_tasks:
        task, created = Task.objects.get_or_create(
            name=item,
            modality=tabular_modality_id
        )

class Migration(migrations.Migration):

    dependencies = [
        ("modality_app", "0003_task_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
        migrations.RunPython(create_tasks)
    ]
