# Generated by Django 5.1.5 on 2025-05-18 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("modality_app", "0004_remove_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="modality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="modality_app.modality"
            ),
        ),
        migrations.CreateModel(
            name="Method",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "modality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modality_app.modality",
                    ),
                ),
            ],
        ),
    ]
