# Generated by Django 5.1.5 on 2025-05-18 13:03

from django.db import migrations, models

def create_methods(apps, schema_editor):
    Modality = apps.get_model('modality_app', 'Modality')
    Method = apps.get_model('modality_app', 'Method')
    nlp_tasks = ['Text Classification', 'Question Answering']
    tabular_tasks = ['Tabular Classification']

    computer_vision_modality_id = Modality.objects.get(name='Computer Vision')
    nlp_modality_id = Modality.objects.get(name='Natural Language Processing')
    tabular_modality_id = Modality.objects.get(name='Tabular Processing')

    computer_vision_methods = ['GradCAM']
    nlp_tabular_methods = ['SHAP']

    for item in computer_vision_methods:
        method, created = Method.objects.get_or_create(
            name=item,
            modality=computer_vision_modality_id
        )

    for item in nlp_tabular_methods:
        method, created = Method.objects.get_or_create(
            name=item,
            modality=nlp_modality_id
        )

    for item in nlp_tabular_methods:
        method, created = Method.objects.get_or_create(
            name=item,
            modality=tabular_modality_id
        )

class Migration(migrations.Migration):

    dependencies = [
        ("modality_app", "0005_alter_task_modality_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="method",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(create_methods),
    ]
