# Generated by Django 5.1.5 on 2025-05-05 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Explanation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("data", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("task", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("method", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("minio_path", models.CharField(max_length=255, default='')),
            ],
        ),
    ]
